version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilerr
  settings:
    errcheck:
      check-type-assertions: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Printf
        - fmt.Print
        - fmt.Fprintln
        - fmt.Println
        - (io.Writer).Write
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/cobra.Command).ParseFlags
        - (*encoding/json.Encoder).Encode
        - encoding/json.Unmarshal
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - rangeValCopy
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G104
        - G301
        - G304
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: defer.*Close\(\)
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
